-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_exthours_project_contact`;
DROP TABLE IF EXISTS `civicrm_exthours_entry_activity`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_exthours_entry_activity
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_exthours_entry_activity` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique EntryActivity ID',
     `external_id` int unsigned    COMMENT 'External ID (ex: kimai timeEntryID)',
     `activity_id` int unsigned    COMMENT 'FK to Activity' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_exthours_entry_activity_activity_id FOREIGN KEY (`activity_id`) REFERENCES `civicrm_activity`(`id`) ON DELETE CASCADE  
)    ;

-- /*******************************************************
-- *
-- * civicrm_exthours_project_contact
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_exthours_project_contact` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique ProjectContact ID',
     `external_id` int unsigned    COMMENT 'External ID (ex: kimai projectID)',
     `contact_id` int unsigned    COMMENT 'FK to Contact' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_exthours_project_contact_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE  
)    ;

 